
public class ExceptionTest {

	public static void main(String[] args) {
		
		/*int waitTime = 12;
	    try
	    {
	        System.out.println("Try block entered");
	    if (waitTime > 30)
	    {
	        throw new Exception("Time Limit Exceeded");            
	    }
	    System.out.println("Leaving try block");
	    }
	    catch (Exception e)
	    {
	        System.out.println("Exception: " + e.getMessage());
	    }
	    System.out.println("After catch block");
	    
	    int[] numbers = new int[5];
	    for (int i = 0; i < numbers.length; i++)
	    {
	        numbers[i] = i * 2;
	    }
	    try 
	    {
	        System.out.println(numbers[5]);        
	    }
	    catch (ArrayIndexOutOfBoundsException e)
	    {
	        System.out.println("ArrayIndexOutOfBoundsException caught");
	    }
	    //a
	    int dividend = 1;
	    int divisor = 0;
	    int quotient = dividend/divisor;
	    System.out.println(quotient);
	    //b
	    int[] listOfInts = new int[6];
	    System.out.println(listOfInts[6]);
	    //c
	    String[] listOfStrings = new String[6];
	    System.out.println(listOfStrings[6].length());
	    //d
	    String[] listOfStrings = new String[6];
	    System.out.println(listOfStrings[5].length());
	    //e
	    String s = "abc";
	    System.out.println(s.charAt(3));
	    //f*/
	    String s = "12.XXX";
	    Double d = Double.parseDouble(s);
	    //g
	    //Object o = new Object();
	    //String s = (String) o;
	    
	    
	    

	}

}
